### PR TITLE
Feature/openhab

### PR DESCRIPTION
**Pull request by moesterheld**
Instructions for installation on openHABian and using openHAB things in Node-RED.
BigTimer is my favorite timing node for scheduling

PS. The diff in the first commit looks really weird.

### CODE REVIEW

**Comment by naimo84** [comment]
Many many thanks for contributing 👍 

But as you said, the first Commit looks weird. Even the result ;)

image

**Comment by naimo84** [comment]
Perhaps some autoformating Extension? 

And due to the contribution guidelines of awesome, every description starts with an uppercase character and ends with a period :)

**Comment by moesterheld** [comment]
Markdown all-in-one extension in VSCode was the culprit.

Looks correct now.

Happy weekend!

**Comment by naimo84** [comment]
perfect, thanks again

happy weekend 😉

**Pull request merged**
